// Filename: apps/eva-school-web/src/api/questionService.ts

import axios from 'axios';
import { auth } from '../firebase'; // You already have this file
import { Question } from '@eva-ecosystem-nx/data-access';

// Define the base URL for our API.
const API_URL = 'http://localhost:5000/api';

// Create an Axios instance that will automatically attach the auth token to requests.
const axiosInstance = axios.create({
  baseURL: API_URL,
});

axiosInstance.interceptors.request.use(async (config) => {
  const user = auth.currentUser;
  if (user) {
    const token = await user.getIdToken();
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});


// Define the data structure for creating a new question.
// We use our shared `Question` interface and omit fields generated by the backend.
type CreateQuestionData = Omit<Question, '_id' | 'createdAt' | 'createdBy'>;

/**
 * Creates a new question in the database via the API.
 * @param questionData - The data for the new question.
 * @returns The newly created question document from the server.
 */
export const createQuestion = async (questionData: CreateQuestionData): Promise<Question> => {
  try {
    const response = await axiosInstance.post('/questions', questionData);
    return response.data;
  } catch (error) {
    console.error("Error creating question:", error);
    // In a real app, we would handle this error more gracefully in the UI
    throw error;
  }
};

// We will add getQuestions, updateQuestion, etc. here later